services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - ISC_CPF_MERGE_FILE=/irisdev/app/merge.cpf
      - DOCKER_BUILDKIT=1
    ports:
      - 1972
      - 55038:52773
      - 53773
      - 4040:4040
    command:
      - --check-caps false
    volumes:
      - ./:/home/irisowner/dev
      #- ./entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
      - ./src/grongier:/usr/irissys/mgr/python/grongier